apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  PORT: "3000"
  MONGO_URI: "mongodb://todoappuser:verysecuredpassword2024@mongo:27017?authMechanism=SCRAM-SHA-256"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: todo-api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: todo-app-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3000
  type: LoadBalancer